type = "ingredients"

[example_ingredient]
unit = "gram"
price_per_unit = 0.01
purchase_increments = [ [500.0, 5.00], [1000.0, 10.00] ]
diet_incompat = ["beef", "vegetarian", "vegan"]

[rice]
unit = "gram" # Density 195g / cup
price_per_unit = 0.005
purchase_increments = [ [1000.0, 5.00], [5000.0, 25.00], [10000.0, 50.00] ]
diet_incompat = []

[soy_sauce]
unit = "milliliter"
price_per_unit = 0.005
purchase_increments = [ [1000.0, 5.00], [5000.0, 25.00], [10000.0, 50.00] ]
diet_incompat = ["soy"]

[egg]
unit = "discrete"
price_per_unit = 0.41667
purchase_increments = [ [12.0, 5.00], [24.0, 10.00] ]
diet_incompat = ["egg", "vegan"]

[bacon]
unit = "discrete"
price_per_unit = 0.5
purchase_increments = [ [10.0, 5.00], [20.0, 10.00] ]
diet_incompat = ["pork", "vegetarian", "vegan"]
