type = "recipe"
name = "Cacio e Pepe"
author = "Felicity Cloake"
lastUpdated = "2026-06-02"

# Cacio e pepe recipe from The Guardian
# https://www.theguardian.com/lifeandstyle/wordofmouth/2016/nov/03/how-to-make-the-perfect-cacio-e-pepe
[ingredients]
spaghetti = "200g"              # 200g spaghetti
cheese_pecorino_romano = "80g"  # 80g pecorino romano cheese
peppercorn_black_whole = "3.5g" # 3.5g whole black peppercorns
