# Milk bread recipe from Cooking Tree YouTube channel
# https://www.youtube.com/watch?v=z7xaYAnacQo
type = "recipe"
name = "Milk Bread - Cooking Tree"
author = "Cooking Tree"
lastUpdated = "2026-09-18"

[ingredients]
milk = "150g"
egg = "35g" # Slightly less than one egg. Save the rest for egg wash.
sugar = "30g"
salt = "5g"
instant dry yeast = "4.5g"
honey = "10g"
"bread flour" = "260g"
"unsalted butter" = "35g"
