type = "recipe"
name = "Milk Bread Rolls"
author = "Joshua Weissman"
lastUpdated = "2026-06-02"

# Joshua Weissman Milk Bread
# https://www.joshuaweissman.com/post/greatest-dinner-rolls
[ingredients]
"bread flour" = "340g"  # 340g bread flour (320 for dough, 20 for tangzhong)
"water" = "27g"
"whole milk" = "180g"   # 180g whole milk (120 for dough, 60 for tangzhong)
"yeast" = "9g"
"salt" = "3g"
"butter" = "98g"
"egg" = 1
"garlic clove" = 2
