type = "ingredient"
name = "salt"
lastUpdated = "2026-09-26"

# Density for Morton's kosher salt according to King Arthur Flour
# https://www.kingarthurbaking.com/learn/ingredient-weight-chart
density.amount = "16"
density.unit = "g/tsp"
purchase_increments = []

[restrictions.dietary]
animalProduct = false
meat = false
egg = false
dairy = false
gluten = false
treeNuts = false
sesame = false
shellfish = false

[restrictions.religious]
halal = true
kosher = true
leavened = false
